[versions]
paperweight = "2.0.0-beta.19"
kotlin = "2.2.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
